### ISSUE TITLE
Could not parse smart contract with "unchecked block" syntax

### ISSUE THREAD

**Issue by edilsalvador** [NomicFoundation/truffle-flattener#77] opened 2021-05-11 10:43 UTC
When I flatten a certain smart contract that uses openzeppelin's SafeMath library I'm getting this error:
`Error: Could not parse @openzeppelin/contracts/utils/math/SafeMath.sol for extracting its imports: ParserError: missing ';' at '{'`

Upon investigation, flattening fails when encountering an `unchecked block`.
`unchecked block` is a valid solidity syntax introduced since `0.8.0`, check reference [here](https://docs.soliditylang.org/en/v0.8.0/control-structures.html#checked-or-unchecked-arithmetic).

Sample code to reproduce the error:
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

library SafeMath {
    . . .
    function tryDiv(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        unchecked {
            if (b == 0) return (false, 0);
            return (true, a / b);
        }
    }
   . . .
}
```

**Comment by sdelvalle57** [comment] 2021-05-26 02:14
Did you get to solve this?

**Comment by MrClottom** [comment] 2021-06-17 10:28
Having the same issue here.

**Comment by kabl** [comment] 2021-06-25 09:34
same issue here...

**Comment by AymericNoel** [comment] 2021-07-05 12:43
Same here...

**Comment by fforbeck** [comment] 2021-07-06 20:14
Same issue

**Comment by jplew** [comment] 2021-07-09 07:49
The problem is due to an outdated version of @solidity-parser/parser. See this PR: https://github.com/nomiclabs/truffle-flattener/pull/81

If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.

**Comment by fedeb95** [comment] 2021-07-09 07:58
> 
> 
> The problem is due to an outdated version of @solidity-parser/parser. See this PR: #81
> 
> If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.

you can also npm package, then npm install the artifact and still use truffle-flattener system wide :) in case you got scripts depending on it

**Comment by AymericNoel** [comment] 2021-07-09 08:06
> > The problem is due to an outdated version of @solidity-parser/parser. See this PR: #81
> > If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.
> 
> you can also npm package, then npm install the artifact and still use truffle-flattener system wide :) in case you got scripts depending on it

You can also do `npm i https://github.com/jplew/truffle-flattener` that will replace current `truffle-flattener` package with branch linked in PR #81. It works fine

**Comment by edilsalvador** [comment] 2021-07-10 08:02
Confirming that PR #80 / #81 fix the issue. Thanks @fedeb95 & @jplew 👍

**Comment by ngduc** [comment] 2021-07-16 01:33
The parser lib (dependency) is outdated. Those PRs need to be merged to upgrade it.
This one should work https://github.com/ngduc/flatten-sol

**Comment by harsh-im** [comment] 2021-07-23 08:06
> > > The problem is due to an outdated version of @solidity-parser/parser. See this PR: #81
> > > If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.
> > 
> > 
> > you can also npm package, then npm install the artifact and still use truffle-flattener system wide :) in case you got scripts depending on it
> 
> You can also do `npm i https://github.com/jplew/truffle-flattener` that will replace current `truffle-flattener` package with branch linked in PR #81. It works fine

This is not working as I am getting the same error

**Comment by cheffNFT** [comment] 2021-10-30 10:09
still having the same situation here

**Comment by Joachim-Lebrun** [comment] 2021-12-14 07:54
thanks for solving the issue @jplew 😊

**Comment by baoduy** [comment] 2022-01-19 01:45
I still got the same issue today. I'm using the truffle-flattener **1.5.0** now

**Comment by mrx23dot** [comment] 2022-01-31 22:34
only this one worked for me:
`sudo npm install "https://github.com/fedeb95/truffle-flattener.git#master" -g --save`

**Comment by alcuadrado** [comment] 2022-02-24 16:11
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._

**Closed by alcuadrado** 2022-02-24 16:11 UTC

**Comment by fedeb95** [comment] 2022-02-24 16:14
so does it work now for unchecked block? was it solved?

**Comment by alcuadrado** [comment] 2022-02-24 16:15
It should be.
